proxy-providers:
  VPS:
    url: ""
    type: http
    interval: 86400
    health-check:
      enable: true
      url: https://www.gstatic.com/generate_204
      interval: 300
    proxy: ç›´è¿
  VPS69:
    url: ""
    type: http
    interval: 86400
    health-check:
      enable: true
      url: https://www.gstatic.com/generate_204
      interval: 300
    proxy: ç›´è¿
    
proxies:
  - {name: ç›´è¿, type: direct, udp: true}

proxy-groups:
  - {name: ğŸš€ å›½å¤–ä»£ç†, type: select, proxies: [ğŸŒ å…¨éƒ¨èŠ‚ç‚¹, ç›´è¿]}
  - {name: ğŸŒ å›½å†…ç›´è¿, type: select, proxies: [ç›´è¿, ğŸš€ å›½å¤–ä»£ç†]}
  - {name: ğŸŸ æ¼ç½‘ä¹‹é±¼, type: select, proxies: [ğŸš€ å›½å¤–ä»£ç†, ç›´è¿, ğŸŒ å…¨éƒ¨èŠ‚ç‚¹]}
  - {name: ğŸŒ å…¨éƒ¨èŠ‚ç‚¹, type: select, include-all: true}

# è§„åˆ™åŒ¹é…
# æ­¤è§„åˆ™éƒ¨åˆ†æ²¡æœ‰åšé˜²æ³„éœ²å¤„ç†ï¼Œå› ä¸ºå¼Šä¸¥é‡å¤§äºåˆ©ï¼
rules:
  - RULE-SET,private_domain,ğŸŒ å›½å†…ç›´è¿
  - RULE-SET,proxylite,ğŸš€ å›½å¤–ä»£ç†
  - RULE-SET,direct,ğŸŒ å›½å†…ç›´è¿
  - RULE-SET,google_cn,ğŸŒ å›½å†…ç›´è¿
  - RULE-SET,category_gamescn,ğŸŒ å›½å†…ç›´è¿
  - RULE-SET,category_aicn,ğŸŒ å›½å†…ç›´è¿
  - RULE-SET,category_mediacn,ğŸŒ å›½å†…ç›´è¿
  - RULE-SET,microsoftcn,ğŸŒ å›½å†…ç›´è¿
  - RULE-SET,download,ğŸŒ å›½å†…ç›´è¿
  - RULE-SET,mydirect,ğŸŒ å›½å†…ç›´è¿
  - RULE-SET,myproxy,ğŸš€ å›½å¤–ä»£ç†
  - RULE-SET,youtube_domain,ğŸš€ å›½å¤–ä»£ç†
  - RULE-SET,google_domain,ğŸš€ å›½å¤–ä»£ç†
  - RULE-SET,github_domain,ğŸš€ å›½å¤–ä»£ç†
  - RULE-SET,telegram_domain,ğŸš€ å›½å¤–ä»£ç†
  - RULE-SET,netflix_domain,ğŸš€ å›½å¤–ä»£ç†
  - RULE-SET,paypal_domain,ğŸš€ å›½å¤–ä»£ç†
  - RULE-SET,onedrive_domain,ğŸš€ å›½å¤–ä»£ç†
  - RULE-SET,microsoft_domain,ğŸš€ å›½å¤–ä»£ç†
  - RULE-SET,speedtest_domain,ğŸš€ å›½å¤–ä»£ç†
  - RULE-SET,tiktok_domain,ğŸš€ å›½å¤–ä»£ç†
  - RULE-SET,category_games,ğŸš€ å›½å¤–ä»£ç†
  - RULE-SET,gfw_domain,ğŸš€ å›½å¤–ä»£ç†
  - RULE-SET,geolocation-!cn,ğŸš€ å›½å¤–ä»£ç†
  - RULE-SET,cn_domain,ğŸŒ å›½å†…ç›´è¿

  - RULE-SET,google_ip,ğŸš€ å›½å¤–ä»£ç†,no-resolve
  - RULE-SET,netflix_ip,ğŸš€ å›½å¤–ä»£ç†,no-resolve
  - RULE-SET,telegram_ip,ğŸš€ å›½å¤–ä»£ç†,no-resolve
  - RULE-SET,cn_ip,ğŸŒ å›½å†…ç›´è¿,no-resolve
  - MATCH,ğŸŸ æ¼ç½‘ä¹‹é±¼

# è§„åˆ™é›†
rule-anchor:
  ip: &ip {type: http, interval: 86400, behavior: ipcidr, format: mrs}
  domain: &domain {type: http, interval: 86400, behavior: domain, format: mrs}
  class: &class {type: http, interval: 86400, behavior: classical, format: text}
rule-providers:
  private_domain: { <<: *domain, url: "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/private.mrs"}
  proxylite: { <<: *domain, url: "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo-lite/geosite/proxy.mrs"}
  direct:  { <<: *class, url: "https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Direct/Direct.list"}
  google_cn: { <<: *domain, url: "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/google-cn.mrs"}
  category_gamescn: { <<: *domain, url: "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/category-games@cn.mrs"}
  category_aicn: { <<: *domain, url: "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/category-ai-cn.mrs"}
  category_mediacn: { <<: *domain, url: "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/category-media-cn.mrs"}
  microsoftcn: { <<: *domain, url: "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/microsoft@cn.mrs"}
  download: { <<: *class, url: "https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Download/Download.list"}
  mydirect: { <<: *class, url: "https://raw.githubusercontent.com/hotren1977/clashrule/main/mydirect.list"}
  myproxy: { <<: *class, url: "https://raw.githubusercontent.com/hotren1977/clashrule/main/myproxy.list"}
  youtube_domain: { <<: *domain, url: "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/youtube.mrs"}
  google_domain: { <<: *domain, url: "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/google.mrs"}
  github_domain: { <<: *domain, url: "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/github.mrs"}
  telegram_domain: { <<: *domain, url: "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/telegram.mrs"}
  netflix_domain: { <<: *domain, url: "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/netflix.mrs"}
  paypal_domain: { <<: *domain, url: "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/paypal.mrs"}
  onedrive_domain: { <<: *domain, url: "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/onedrive.mrs"}
  microsoft_domain: { <<: *domain, url: "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/microsoft.mrs"}
  speedtest_domain: { <<: *domain, url: "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/ookla-speedtest.mrs"}
  tiktok_domain: { <<: *domain, url: "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/tiktok.mrs"}
  category_games: { <<: *domain, url: "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/category-games.mrs"}
  gfw_domain: { <<: *domain, url: "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/gfw.mrs"}
  geolocation-!cn: { <<: *domain, url: "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/geolocation-!cn.mrs"}
  cn_domain: { <<: *domain, url: "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/cn.mrs"}
  
  cn_ip: { <<: *ip, url: "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geoip/cn.mrs"}
  google_ip: { <<: *ip, url: "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geoip/google.mrs"}
  telegram_ip: { <<: *ip, url: "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geoip/telegram.mrs"}
  netflix_ip: { <<: *ip, url: "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geoip/netflix.mrs"}
